name: Build and Test API

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t todo-api:latest ./backend
          echo "Docker image built successfully!"


      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: todo-api:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker image
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' todo-api:latest || docker inspect --format='{{.Id}}' todo-api:latest)
          cosign sign --yes "$DIGEST"
